name: Eggplant Runner Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Run-Test-Configuration:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@main
        with:
          serverURL: "http://localhost:8000"
          clientID: "client:dai:agent:integration"
          testConfigID: "2fa6e754-a238-4654-9ba7-a354d0dc973e" # Test configuration which need to perform execution
          clientSecret: "a6a57e53-5151-454d-823f-f27acb6a7e27" # Eggplant DAI service client secret
          # gitlabAccessToken: ""
          # Alternatively, DAI client secret can be set as repo secret
          # by going to GitHub Settings > Secrets > Actions
          # clientSecret: "${{secrets.DAI_CLIENT_SECRET}}"
